question_data = [
{"text": "A slug's blood is green.", "answer": "True"},
{"text": "The loudest animal is the African Elephant.", "answer": "False"},
{"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
{"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
{"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
{"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
{"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
{"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
{"text": "Google was originally called 'Backrub'.", "answer": "True"},
{"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
{"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
{"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
]

question_data_2 = [
  {"text": "The unicorn is the national animal of Scotland.", "answer": "True"},
  {"text": "The capital of Australia is Sydney.", "answer": "False"},
  {"text": "Bananas grow on trees.", "answer": "False"},
  {"text": "Octopuses have three hearts.", "answer": "True"},
  {"text": "Sharks are mammals.", "answer": "False"},
  {"text": "The Great Wall of China is visible from the Moon.", "answer": "False"},
  {"text": "Lightning never strikes the same place twice.", "answer": "False"},
  {"text": "Humans can distinguish over a trillion different smells.", "answer": "True"},
  {"text": "Goldfish only have a memory of three seconds.", "answer": "False"},
  {"text": "The human nose and ears never stop growing.", "answer": "True"},
  {"text": "The Atlantic Ocean is the largest ocean on Earth.", "answer": "False"},
  {"text": "There are more stars in space than grains of sand on Earth.", "answer": "True"},
  {"text": "Some cats are allergic to humans.", "answer": "True"},
  {"text": "The inventor of the lightbulb was Thomas Edison.", "answer": "True"},
  {"text": "Bats are blind.", "answer": "False"},
  {"text": "Napoleon Bonaparte was extremely short.", "answer": "False"},
  {"text": "The longest river in the world is the Amazon River.", "answer": "False"},
  {"text": "Adult humans have fewer bones than babies.", "answer": "True"},
  {"text": "You can sneeze in your sleep.", "answer": "False"},
  {"text": "Honey never spoils.", "answer": "True"},
  {"text": "There is a species of jellyfish that is biologically immortal.", "answer": "True"},
  {"text": "Penguins can fly.", "answer": "False"},
  {"text": "The Eiffel Tower can grow taller in the summer.", "answer": "True"},
  {"text": "Humans share about 98% of their DNA with chimpanzees.", "answer": "True"},
  {"text": "A group of flamingos is called a 'flamboyance'.", "answer": "True"},
  {"text": "Mount Everest is the closest point to space from Earth.", "answer": "False"},
  {"text": "Water conducts electricity.", "answer": "False"},
  {"text": "Diamonds are made of carbon.", "answer": "True"},
  {"text": "The human brain is the heaviest organ in the body.", "answer": "False"},
  {"text": "The Statue of Liberty was a gift from France.", "answer": "True"},
  {"text": "Antarctica is the driest continent on Earth.", "answer": "True"},
  {"text": "Humans have more than five senses.", "answer": "True"},
  {"text": "The sun is a planet.", "answer": "False"},
  {"text": "A bolt of lightning is hotter than the surface of the sun.", "answer": "True"},
  {"text": "All deserts are hot.", "answer": "False"},
  {"text": "Slugs have four noses.", "answer": "True"},
  {"text": "Humans can't breathe and swallow at the same time.", "answer": "True"},
  {"text": "The average person walks the equivalent of five times around the world in their lifetime.", "answer": "False"},
  {"text": "Venus is the hottest planet in our solar system.", "answer": "True"},
  {"text": "An octopus has six arms and two legs.", "answer": "True"},
  {"text": "There are more fake flamingos in the world than real ones.", "answer": "True"},
  {"text": "Koalas sleep up to 22 hours a day.", "answer": "True"},
  {"text": "Spiders are insects.", "answer": "False"},
  {"text": "You can see your nose at all times, your brain just ignores it.", "answer": "True"},
  {"text": "You can't hum while holding your nose.", "answer": "True"},
  {"text": "A crocodile cannot stick its tongue out.", "answer": "True"},
  {"text": "The moon has its own light source.", "answer": "False"},
  {"text": "Your foot is the same length as your forearm.", "answer": "True"},
  {"text": "A group of crows is called a murder.", "answer": "True"},
  {"text": "Tomatoes are vegetables.", "answer": "False"},
  {"text": "The name for the shape of Pringles is called a hyperbolic paraboloid.", "answer": "True"},
  {"text": "It rains diamonds on Jupiter and Saturn.", "answer": "True"},
  {"text": "Sound travels faster than light.", "answer": "False"},
  {"text": "You can cry in space.", "answer": "True"},
  {"text": "Humans can live without a spleen.", "answer": "True"},
  {"text": "All polar bears are left-handed.", "answer": "False"},
  {"text": "The speed of a computer mouse is measured in 'Mickeys'.", "answer": "True"},
  {"text": "Shaving makes hair grow back thicker.", "answer": "False"},
  {"text": "Cows have best friends and get stressed when separated.", "answer": "True"},
  {"text": "Elephants are the only animals that can't jump.", "answer": "False"},
  {"text": "Hot water freezes faster than cold water.", "answer": "True"},
  {"text": "Birds are descendants of dinosaurs.", "answer": "True"}
]


# """Check how the dictionaries are working"""
# for i in question_data:
#     print("text: ", i["text"], "answer: ", i["answer"])
